Docker Image CI  # 自动化任务的名字

on:
  push:
    branches: [ "master" ]  # 当 master 分支有代码推送时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 在 GitHub 提供的最新版 Ubuntu 服务器上运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 第一步：把你的代码拉取到 GitHub 服务器上

    - name: Login to Docker Hub
      uses: docker/login-action@v2  # 第二步：登录 Docker Hub
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4  # 第三步：构建镜像并推送
      with:
        context: .
        push: true
        tags: icancnobb/my-webserver:latest  # 自动更新 latest 标签
